### PR TITLE
Add a Handle.net error log page

### LINKED ISSUE #24: Show handle registration errors
**ACCEPTANCE CRITERIA**

- [x] The system maintains a log of registration errors with the handle server 
- [ ] Any administrator logged into the application's user interface can view the errors, if any, with the handle system

### PR DESCRIPTION
**Pull request by little9**
Closes #24

### CODE REVIEW

**Comment by no-reply** [comment]
@little9 can you fix the commit message on this. Not sure how this happened, but it seems to be mislabeled.

**Comment by little9** [comment]
@no-reply Sorry about that, I fixed the message

**Comment by no-reply** [comment]
Maybe we should think about a test that ensures an actually logged handle error shows up on the page?

**Comment by little9** [comment]
What would be the best way to trigger an error in RSpec?

**Comment by no-reply** [comment]
@little9 The error logging tests for `HandleRegistrar` have an example you might consider reusing: https://github.com/curationexperts/epigaea/blob/master/spec/lib/tufts/handle_registrar_spec.rb#L75-L105

The example uses a fake `Connection` object that always raises a handle error as though the server had raised it. If you find yourself reusing that, it might be a good idea to move it into `spec/support/fakes` so you don't have to duplicate it in your specs.

**Comment by no-reply** [comment]
Looks good. Waiting on CI.

**Pull request merged**
