### PR TITLE
Batch controls in dashboard for all works and my works, sortable tables in dashboard

### LINKED ISSUE #441: Make batch select options consistent
Spend up to 2 hours....

Determine how easy it would be to
- [ ] Add batch select to "All Works"
- [ ] Make the same batch options available on the Catalog view, My Works, and All Works

### LINKED ISSUE #491: Sort option on Works list

### LINKED ISSUE #492: Publish option on actions for Works list
It would be nice if, in addition to "edit-delete-highlights-transfer" under the actions option, it was possible to publish from the works page.

### PR DESCRIPTION
**Pull request by little9**
screen shot 2017-11-02 at 7 15 13 pm

screen shot 2017-11-02 at 7 52 35 pm

Closes #441 
Closes #491 
Closes #492

### CODE REVIEW

**Comment by mark-dce** [comment]
@little9 - there should not be a "Batch Delete" option.

*BACKGROUND*
We discussed with Tufts during v1 and the consensus was that it was overly dangerous for relatively limited use cases.  If there's really a need to delete more items at a time than someone can easily do individually via the UI, that should probably be via a custom rake task or console session ONLY AFTER there has been a good backup of the full repository.

**Comment by mark-dce** [comment]
& sorry, I should have thought to call that out in #441

**Comment by little9** [comment]
@mark-dce the button is there by default on the 'My Works' tab, should I remove it there as well?

**Comment by mark-dce** [comment]
@little9 OK, I didn't realize that it came in from Hyrax in some places.  Let's leave it in for now then and show it to Tufts at the next demo.  So I'm happy to merge this as-is once the test suite passes.  It looks like the one failure is related to batch delete, so I'll let you take a look rather than restarting the tests.

**Comment by little9** [comment]
@mark-dce I went ahead and hid the delete buttons in my last commit, we can ask during the demo if they want to bring it back.

**Pull request merged**
